$(document).ready(function(){"use strict";var body=$("body");$(function(){setTimeout(function(){$(".preloader").fadeOut()},1000);});$(".open-close").on("click",function(){body.toggleClass("show-sidebar").toggleClass("hide-sidebar");$(".sidebar-head .open-close i").toggleClass("ti-menu");});$(".right-side-toggle").on("click",function(){$(".right-sidebar").slideDown(50).toggleClass("shw-rside");$(".fxhdr").on("click",function(){body.toggleClass("fix-header");});$(".fxsdr").on("click",function(){body.toggleClass("fix-sidebar");});var fxhdr=$('.fxhdr');if(body.hasClass("fix-header")){fxhdr.attr('checked',true);}
else{fxhdr.attr('checked',false);}});$(function(){var set=function(){var topOffset=60,width=(window.innerWidth>0)?window.innerWidth:this.screen.width,height=((window.innerHeight>0)?window.innerHeight:this.screen.height)-1;if(width<768){$('div.navbar-collapse').addClass('collapse');topOffset=100;}
else{$('div.navbar-collapse').removeClass('collapse');}
if(width<1170){body.addClass('content-wrapper');$(".sidebar-nav, .slimScrollDiv").css("overflow-x","visible").parent().css("overflow","visible");}
else{body.removeClass('content-wrapper');}
height=height-topOffset;if(height<1){height=1;}
if(height>topOffset){$("#page-wrapper").css("min-height",(height)+"px");}},url=window.location,element=$('ul.nav a').filter(function(){return this.href===url||url.href.indexOf(this.href)===0;}).addClass('active').parent().parent().addClass('in').parent();if(element.is('li')){element.addClass('active');}
$(window).ready(set);$(window).bind("resize",set);});(function($,window,document){var panelSelector='[data-perform="panel-collapse"]',panelRemover='[data-perform="panel-dismiss"]';$(panelSelector).each(function(){var collapseOpts={toggle:false},parent=$(this).closest('.panel'),wrapper=parent.find('.panel-wrapper'),child=$(this).children('i');if(!wrapper.length){wrapper=parent.children('.panel-heading').nextAll().wrapAll('<div/>').parent().addClass('panel-wrapper');collapseOpts={};}
wrapper.collapse(collapseOpts).on('hide.bs.collapse',function(){child.removeClass('ti-minus').addClass('ti-plus');}).on('show.bs.collapse',function(){child.removeClass('ti-plus').addClass('ti-minus');});});$(document).on('click',panelSelector,function(e){e.preventDefault();var parent=$(this).closest('.panel'),wrapper=parent.find('.panel-wrapper');wrapper.collapse('toggle');});$(document).on('click',panelRemover,function(e){e.preventDefault();var removeParent=$(this).closest('.panel');function removeElement(){var col=removeParent.parent();removeParent.remove();col.filter(function(){return($(this).is('[class*="col-"]')&&$(this).children('*').length===0);}).remove();}
removeElement();});}(jQuery,window,document));$(function(){$('[data-toggle="tooltip"]').tooltip();});$(function(){$('[data-toggle="popover"]').popover();});$(".list-task li label").on("click",function(){$(this).toggleClass("task-done");});$(".settings_box a").on("click",function(){$("ul.theme_color").toggleClass("theme_block");});$(".collapseble").on("click",function(){$(".collapseblebox").fadeToggle(350);});$('.slimscrollright').slimScroll({height:'100%',position:'right',size:"5px",color:'#dcdcdc'});$('.slimscrollsidebar').slimScroll({height:'100%',position:'right',size:"6px",color:'rgba(0,0,0,0.3)'});$('.chat-list').slimScroll({height:'100%',position:'right',size:"0px",color:'#dcdcdc'});body.trigger("resize");$('.visited li a').on("click",function(e){$('.visited li').removeClass('active');var $parent=$(this).parent();if(!$parent.hasClass('active')){$parent.addClass('active');}
e.preventDefault();});$('#to-recover').on("click",function(){$("#loginform").slideUp();$("#recoverform").fadeIn();});$(".navbar-toggle").on("click",function(){$(".navbar-toggle i").toggleClass("ti-menu").addClass("ti-close");});});