var transWord;$(document).ready(function(e){if(getCookie('locale')=='zh'){$.getJSON("/front_trans_locales/zh.json",function(json){transWord=json;});}else{$.getJSON("/front_trans_locales/en.json",function(json){transWord=json;});}})
function login(email,password){(email===undefined)?email=$("#email").val():true;(password===undefined)?password=$("#password").val():true;if(email===""||password===""){return false;}
firebase.auth().signInWithEmailAndPassword(email,password).then(function(data){firebase.auth().currentUser.getIdToken(true).then(function(data){console.log('granted token');return data;}).then(function(d){setCookie("idToken",d);window.location.replace("/dashboard");});}).catch(function(err){error(err);console.debug(err);});}
function wipeLocal(){localStorage.removeItem("facebookUserInfo");localStorage.removeItem("twitterUserInfo");}
function error(err,dur){var duration=dur||3000;console.log(duration);var text="";switch(err.code){case "auth/invalid-email":text=transWord.signin_warn1;break;case "auth/user-disabled":text=transWord.signin_warn2;break;case "auth/user-not-found":text=transWord.signin_warn3;break;case "auth/wrong-password":text=transWord.signin_warn4;break;case "auth/no-credentials":text=transWord.signin_warn5;break;default:text=transWord.signin_warn6;break;}
$("#signInButton").removeClass("btn-outline-primary").addClass("btn-outline-danger").text(text);setTimeout(function(){$("#signInButton").removeClass("btn-outline-danger").addClass("btn-outline-primary").text(transWord.signin_signin);},duration);}
function facebookLogin(){var provider=new firebase.auth.FacebookAuthProvider();var scopes=["email","public_profile","user_friends"];scopes.forEach(function(s){provider.addScope(s);});firebase.auth().signInWithPopup(provider).then(function(data){localStorage.setItem("facebookUserInfo",JSON.stringify(data.additionalUserInfo));firebase.auth().currentUser.getIdToken(true).then(function(token){setCookie("idToken",token);token=decodeToken(token);if(token){window.location.replace("/dashboard")}
else{alert(transWord.signin_warn7)}});}).catch(function(err){alert(transWord.signin_warn8);});}
function twitterLogin(){var provider=new firebase.auth.TwitterAuthProvider();firebase.auth().signInWithPopup(provider).then(function(data){localStorage.setItem("twitterUserInfo",JSON.stringify(data.additionalUserInfo));firebase.auth().currentUser.getIdToken(true).then(function(token){setCookie("idToken",token);token=decodeToken(token);if(token){window.location.replace("/dashboard")}
else{alert(transWord.signin_warn9)}});}).catch(function(err){alert(transWord.signin_warn10);});}
$("#signInButton").click(function(){login();});$("#facebookButton").click(function(){facebookLogin();});$("#twitterButton").click(function(){twitterLogin();});$("#resetButton").click(function(){$("#resetButton").html(transWord.reset_text1);firebase.auth().sendPasswordResetEmail($("#resetEmail").val()).then(function(data){$("#resetButton").html(transWord.reset_text2);setTimeout(function(){$("#resetButton").html(transWord.reset_text3);},3000);}).catch(function(err){var text="";switch(err.code){case "auth/invalid-email":text=transWord.reset_text4;break;}
$("#resetButton").html(text);setTimeout(function(){$("#resetButton").html(transWord.reset_text3);},3000);});});